ARG PHP_VERSION=7.2
FROM php:${PHP_VERSION}-fpm

ARG PHP_USER
ARG PHP_UID
ARG PHP_WORKDIR

# Dependencies
RUN apt-get update \
    && apt-get install -y zip unzip git

# PHP Configuration
RUN docker-php-ext-install pdo_mysql
RUN mv "${PHP_INI_DIR}/php.ini-development" "${PHP_INI_DIR}/php.ini"
RUN echo "memory_limit=-1" > "${PHP_INI_DIR}/conf.d/z_bofhers.ini"

# Composer executable and misc. utilities
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
COPY ./scripts/bofhers_php/bofhers_php_entrypoint.sh /usr/local/bin

# PHP user permissions
RUN useradd -G www-data,root -u ${PHP_UID} -d /home/${PHP_USER} ${PHP_USER}
RUN mkdir -p /home/${PHP_USER}/.composer && \
    chown -R ${PHP_USER}: /home/${PHP_USER}/

# User workdir
WORKDIR ${PHP_WORKDIR}
USER ${PHP_USER}

# Entrypoint
ENTRYPOINT ["bofhers_php_entrypoint.sh"]
